# Generated by Django 5.1.5 on 2025-01-28 07:56

import django.db.models.deletion
import django_extensions.db.fields
import salary_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ESIC')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to=salary_management.models._attachments_esic)),
            ],
        ),
        migrations.CreateModel(
            name='Gratuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gratuity')),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Provident Fund')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Professional Tax')),
            ],
        ),
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TDS')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost to Cut Salary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salary',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to=settings.AUTH_USER_MODEL)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='salary_management.salary')),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Allowance')),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='House Rent Allowance')),
                ('uniform', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Uniform Allowance')),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transport Allowance')),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Medical Allowance')),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conveyance Allowance')),
                ('other', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Allowance')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='salary_management.salary')),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('other', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Deduction')),
                ('esic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary_management.esic')),
                ('gratuity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary_management.gratuity')),
                ('pf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary_management.pf')),
                ('pt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary_management.pt')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='salary_management.salary')),
                ('tds', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary_management.tds')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
            },
        ),
    ]
