# Generated by Django 5.1.5 on 2025-01-27 13:34

import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
import user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('organization_management', '0002_department_designation_technology'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user_management.models.profile_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('landmark', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='user_management.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='present_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to='user_management.address'),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_management.technology')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='user_management.skill'),
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.CharField(blank=True, max_length=10, null=True)),
                ('adharcard', models.CharField(blank=True, max_length=12, null=True)),
                ('voterid', models.CharField(blank=True, max_length=10, null=True)),
                ('passport', models.CharField(blank=True, max_length=8, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True)),
                ('maritial_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('emergency_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=4, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('offered', 'Offered'), ('probation', 'Probation'), ('confirmed', 'Confirmed'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('relieved', 'Relieved'), ('f_and_f_complete', 'F&F Complete')], max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern'), ('trainee', 'Trainee')], max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_interviewer', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_management.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_management.designation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_management.organization')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_manager', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, to='user_management.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('agreement', models.ImageField(upload_to=user_management.models.user_aggrement)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.userorganizationdetails')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_type', models.CharField(blank=True, choices=[('cgpa', 'CGPA'), ('percentage', 'Percentage')], max_length=12, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=user_management.models.user_qualification_certificate)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
