# Generated by Django 5.1.5 on 2025-01-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0002_department_designation_technology'),
        ('user_management', '0002_user_created_by_user_image_alter_user_email_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankDetail',
        ),
        migrations.RenameModel(
            old_name='UserOrganizationDetails',
            new_name='UserOrganizationDetail',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterModelOptions(
            name='bankdetail',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='useridentity',
            options={'verbose_name': 'User Identity', 'verbose_name_plural': 'User Identities'},
        ),
        migrations.AlterModelOptions(
            name='usermetadata',
            options={'verbose_name': 'User Meta Data', 'verbose_name_plural': 'User Meta Datas'},
        ),
        migrations.AlterModelOptions(
            name='userorganizationdetail',
            options={'verbose_name': 'User Organization Detail', 'verbose_name_plural': 'User Organization Details'},
        ),
        migrations.AlterModelOptions(
            name='userqualification',
            options={'verbose_name': 'User Qualification', 'verbose_name_plural': 'User Qualifications'},
        ),
    ]
