# Generated by Django 5.1.5 on 2025-01-28 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userqualification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('reporting_managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_managers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reporting',
                'verbose_name_plural': 'User Reporting',
            },
        ),
    ]
