# Generated by Django 5.1.5 on 2025-01-28 07:56

import django.db.models.deletion
import django_extensions.db.fields
import review_management.utils.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('created', models.DateField()),
                ('performance_rating', models.IntegerField(choices=review_management.utils.constants.ReviewChoices.get_choices)),
                ('performance_comment', models.TextField(blank=True, null=True)),
                ('delivery_rating', models.IntegerField(choices=review_management.utils.constants.ReviewChoices.get_choices)),
                ('delivery_comment', models.TextField(blank=True, null=True)),
                ('socialization_rating', models.IntegerField(choices=review_management.utils.constants.ReviewChoices.get_choices)),
                ('socialization_comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
