# Generated by Django 5.1.5 on 2025-01-28 07:56

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=12)),
                ('tl_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=12)),
                ('hr_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=12)),
                ('manager_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_reason', models.TextField(blank=True, null=True)),
                ('special_type', models.CharField(choices=[('maternity_leave', 'Maternity Leave'), ('marriage_leave', 'Marriage Leave')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.IntegerField(default=0)),
                ('emergency_leave', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_type', models.CharField(choices=[('casual_leave', 'Casual Leave'), ('emergency_leave', 'Emergency Leave')], max_length=20)),
                ('leave_period', models.CharField(choices=[('first_half', 'First Half'), ('second_half', 'Second Half'), ('full_day', 'Full Day')], max_length=20)),
                ('is_special_leave', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavestatus')),
                ('special_leave', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.specialleave')),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
            },
        ),
    ]
